# Generated by Django 5.2.3 on 2025-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
