# Generated by Django 5.2.3 on 2025-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contactmessage_contactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
