# Generated by Django 5.2.3 on 2025-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contactsettings_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='whatsapp_group',
            field=models.URLField(blank=True, null=True),
        ),
    ]
