# Generated by Django 5.2.3 on 2025-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clubofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubofficial',
            name='instagram',
            field=models.URLField(blank=True, help_text='Paste Instagram profile link', null=True),
        ),
        migrations.AddField(
            model_name='clubofficial',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Paste full WhatsApp link e.g. https://wa.me/2547XXXXXXX', null=True),
        ),
        migrations.AlterField(
            model_name='clubofficial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
